name: Lint (Ruff)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: python -m pip install --upgrade pip && pip install ruff

      - name: Ruff check (full repo)
        run: ruff check . --format=github

      - name: Generate SARIF report
        run: ruff check . --output-format=sarif > ruff.sarif || true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ruff.sarif

      - name: Upload text report artifact
        if: always()
        run: ruff check . > ruff.txt || true
      
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ruff-report
          path: ruff.txt

